export const STORES = [
  {
    id: "PS-LG1",
    name: "Pwnshop Lagos Island",
    address: "15 Broad Street, Lagos Island, Lagos",
    state: "Lagos",
    stateColor: "#006400",
    phone: "+2341-462-0001",
    hours: "Mon–Sat: 8am–7pm | Sun: 10am–4pm",
    landmark: "Opposite First Bank HQ",
  },
  {
    id: "PS-LG2",
    name: "Pwnshop Ikeja",
    address: "42 Allen Avenue, Ikeja, Lagos",
    state: "Lagos",
    stateColor: "#006400",
    phone: "+2341-462-0002",
    hours: "Mon–Sat: 8am–8pm | Sun: 10am–5pm",
    landmark: "Near Computer Village junction",
  },
  {
    id: "PS-AB1",
    name: "Pwnshop Abuja Central",
    address: "Plot 1077 Adetokunbo Ademola Crescent, Wuse II, Abuja",
    state: "FCT Abuja",
    stateColor: "#8B0000",
    phone: "+2349-070-0001",
    hours: "Mon–Fri: 9am–6pm | Sat: 9am–5pm",
    landmark: "Close to Transcorp Hilton Hotel",
  },
  {
    id: "PS-PH1",
    name: "Pwnshop Port Harcourt",
    address: "3 Rumuola Road, Port Harcourt, Rivers",
    state: "Rivers",
    stateColor: "#00008B",
    phone: "+2348-084-0001",
    hours: "Mon–Sat: 8am–7pm | Sun: 11am–4pm",
    landmark: "By Rumuola roundabout",
  },
  {
    id: "PS-KN1",
    name: "Pwnshop Kano",
    address: "22 Ibrahim Taiwo Road, Kano",
    state: "Kano",
    stateColor: "#556B2F",
    phone: "+2348-064-0001",
    hours: "Mon–Sat: 8am–6pm",
    landmark: "Near Kano Central Mosque",
  },
  {
    id: "PS-IB1",
    name: "Pwnshop Ibadan",
    address: "14 Ring Road, Challenge, Ibadan, Oyo",
    state: "Oyo",
    stateColor: "#8B4513",
    phone: "+2348-022-0001",
    hours: "Mon–Sat: 8am–7pm | Sun: 10am–3pm",
    landmark: "Challenge interchange, opposite GTBank",
  },
  {
    id: "PS-EN1",
    name: "Pwnshop Enugu",
    address: "7 Ogui Road, Independence Layout, Enugu",
    state: "Enugu",
    stateColor: "#4B0082",
    phone: "+2348-042-0001",
    hours: "Mon–Sat: 9am–6pm",
    landmark: "Beside Polo Park Mall",
  },
  {
    id: "PS-KD1",
    name: "Pwnshop Kaduna",
    address: "31 Ahmadu Bello Way, Kaduna",
    state: "Kaduna",
    stateColor: "#2F4F4F",
    phone: "+2348-062-0001",
    hours: "Mon–Sat: 8am–6pm",
    landmark: "Near Barau Dikko Teaching Hospital",
  },
  {
    id: "PS-AK1",
    name: "Pwnshop Akure",
    address: "18 Oyemekun Road, GRA, Akure, Ondo",
    state: "Ondo",
    stateColor: "#B8860B",
    phone: "+2348-034-0001",
    hours: "Mon–Sat: 9am–6pm | Sun: 11am–3pm",
    landmark: "Close to Akure Government House",
  },
  {
    id: "PS-AS1",
    name: "Pwnshop Asaba",
    address: "55 Nnebisi Road, Asaba, Delta",
    state: "Delta",
    stateColor: "#006400",
    phone: "+2348-056-0001",
    hours: "Mon–Sat: 8am–7pm | Sun: 10am–4pm",
    landmark: "Near Asaba Shopping Mall",
  },
];
